# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g NuGetKeyVaultSignTool'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'for f in $(find ./ -name ''*.nupkg''); do echo ~/.dotnet/tools/NuGetKeyVaultSignTool.exe sign "$f" --file-digest sha256 --timestamp-rfc3161 http://timestamp.digicert.com --timestamp-digest sha256 --azure-key-vault-url "$EVAULTURL" --azure-key-vault-client-id "$EVAULTID" --azure-key-vault-client-secret "$EVAULTSECRET" --azure-key-vault-certificate "$VAULTCERTNAME"; done'
  displayName: NuGetKeyVaultSignTool
  env:
    EVAULTID: $(VaultId)
    EVAULTSECRET: $(VaultSecret)
    EVAULTURL: $(VaultUrl)
    EVAULTCERTNAME: $(VaultCertname)
