# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: off
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '$([System.DateTime]::Now.ToString(`yyyyMMdd`)).$([System.DateTime]::Now.ToString(`HHmm`))'
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new([System.Convert]::FromBase64String($env:CodeCertificate));
      Get-ChildItem "./" -R -Filter *.nupkg | ForEach-Object { Set-AuthenticodeSignature -FilePath $_.FullName -Certificate $certificate; }'
  env:
    CodeCertificate: $(Codesign2018)