# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g NuGetKeyVaultSignTool'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '$certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new([System.Convert]::FromBase64String($(Code-Certificate)));
      Get-ChildItem "./" -R -Filter *.nupkg | ForEach-Object { Set-AuthenticodeSignature -FilePath $_.FullName -Certificate $certificate; }'
  env:
    Code-Certificate: $(Codesign2018)